import LNB from '@/components/LNB';
import { ThemeProvider } from '@/components/ThemeProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Minsung_Portfolio',
  // description: 'Generated by create next app',
  openGraph: {
    title: 'Minsung_Portfolio',
    description: 'my portfolio website',
    images: [
      {
        url: '/thumbnail.png',
        width: 1200,
        height: 630,
        alt: 'thumbnail',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Minsung_Portfolio',
    description: 'my portfolio website',
    images: ['/thumbnail.png'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <LNB />
          <main className="ml-48 p-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
